### ISSUE TITLE
datasource-client-digest只采集了部分日志

### ISSUE THREAD

**Issue by rayzeng** [sofastack/sofa-tracer#152]
### Your question

datasource-client-digest.log只有部分日志，只有select 1这种连接探活的日志，而业务正常的select日志没有显示。使用的是druid+mybatis，sofaboot环境。rest接入调用mybatis的mapper执行的select语句。
debug发现StatementTracerInterceptor和ConnectionTraceInterceptor都已正常初始化。什么场景下会出现？什么情况下才会触发拦截器的调用

### Environment

- SOFATracer version:3.0.0
- JVM version (e.g. `java -version`):1.8

**Comment by QilongZhang** [comment]
调试下代码中 dataSource 实例是否是 SmartDataSource 类型，Spring Boot 自动配置的 DataSource 会被wrap成 SmartDataSource.

如果方便，可以提供下复现 Demo.

**Comment by rayzeng** [comment]
是SmartDataSource类型

**Comment by khotyn** [comment]
@rayzeng 有重新问题的 Demo 的吗？有的话会比较好查一点。

**Comment by QilongZhang** [comment]
@rayzeng  我使用 mybatis 测试下，有结果反馈给你。

**Comment by QilongZhang** [comment]
@rayzeng  mybaits 是怎么配置的？ 是通过 xml  还是 mybatis-spring-boot-starter 配置的，另外调试时，执行sql语句是不是没有进入 StatementTracerInterceptor#intercept   方法？

**Comment by glmapper** [comment]
no feedback , i will close current issue , if any other question can reopen it again
