### ISSUE TITLE
 Anytime, anywhere create new Span,but the log isnot print?

### ISSUE THREAD

**Issue by vwyuheng** [sofastack/sofa-tracer#200]
### Describe the bug

同一个请求生命周期内，我想实现随时生成一个新的span，并且单独输出一条日志，
但拿到当前tracer生成新到span后，打印的只是当前组件生成的span，没有输出新的span日志信息
### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@vwyuheng Can you provide a use case or a short code snippet?

**Comment by XiongChaoGoing** [comment]
Looking at SofaTracerSpan ‘s finish method may be helpful to you
