### ISSUE TITLE
dubbo版本问题

### ISSUE THREAD

**Issue by 285976754** [sofastack/sofa-tracer#204]
sofatracer从2.4.0支持dubbo，而且支持dubbo版本是2.7.0的，那2.6.x版本的dubbo支持吗

**Comment by glmapper** [comment]
> sofatracer从2.4.0支持dubbo，而且支持dubbo版本是2.7.0的，那2.6.x 版本的dubbo支持吗

目前是从 2.7.0  版本开始支持

**Comment by 285976754** [comment]
> > sofatracer从2.4.0支持dubbo，而且支持dubbo版本是2.7.0的，那2.6.x 版本的dubbo支持吗
> 
> 目前是从 2.7.0 版本开始支持

希望能兼容支持一下低版本2.5.x及2.6.x

**Comment by glmapper** [comment]
> > > sofatracer从2.4.0支持dubbo，而且支持dubbo版本是2.7.0的，那2.6.x 版本的dubbo支持吗
> > 
> > 
> > 目前是从 2.7.0 版本开始支持
> 
> 希望能兼容支持一下低版本2.5.x及2.6.x

我们会在后续版本考虑下对低版本的兼容问题，如果有兴趣也欢迎提供相关 PR.

**Comment by glmapper** [comment]
[SpringMVC项目如何使用dubbo插件](https://github.com/alipay/sofa-tracer/issues/219)

**Comment by glmapper** [comment]
由于 2.7.2 存在性能问题，并且与 2.7.0 存在兼容性问题，所以 SOFATracer 从  2.4.1  版本开始升级 Dubbo 版本至 2.7.3 。#230
