### ISSUE TITLE
SpringMVC项目如何使用dubbo插件

### ISSUE THREAD

**Issue by spiritme1984** [sofastack/sofa-tracer#219]
官方给出的例子都是基于spring boot项目的，在springMVC项目中使用Dubbo组件，如何实现sofa-tracer-dubbo-plugin ? 都需引入什么依赖，web.xml需要如何配置？

**Comment by glmapper** [comment]
目前 SOFATracer 支持 Dubbo 2.7 版本，埋点实现依赖[Dubbo 调用拦截扩展](https://dubbo.apache.org/zh-cn/docs/dev/impls/filter.html)。因此在 MVC 系统中使用 SOFATracer 对Dubbo 埋点，可参考 [Dubbo 调用拦截扩展](https://dubbo.apache.org/zh-cn/docs/dev/impls/filter.html)的使用，将扩展的 DubboSofaTracerFilter 作用于请求即可

**Comment by spiritme1984** [comment]
谢谢，问一下，我们之后会支持老版本的Dubbo吗？

**Comment by glmapper** [comment]
> 谢谢，问一下，我们之后会支持老版本的Dubbo吗？

请问下，你们目前使用的Dubbo 版本是多少

**Comment by spiritme1984** [comment]
目前我们的版本是2.5.3的版本。。。
