### ISSUE TITLE
why traceId been put in SofaTracerSpanContext, rather than TrancerSpan?

### ISSUE THREAD

**Issue by ghost** [sofastack/sofa-tracer#220]
I mean, I found that the spanId and traceId had been put in SofaTracerSpanContext
what is the function of SofaTracerSpanContext?
And why not put spanId and traceId in Span directly?

**Comment by ghost** [comment]
by studying the code, I think the reason why we need SofaTracerSpanContext is because of the openTracing formation.
SofaTracerSpanContext will be send to server when client invoke RPC, and server will extract SofaTracerSpanContext.

**Comment by ghost** [comment]
Do I understand it correctly?

**Comment by glmapper** [comment]
> by studying the code, I think the reason why we need SofaTracerSpanContext is because of the openTracing formation.
> SofaTracerSpanContext will be send to server when client invoke RPC, and server will extract SofaTracerSpanContext.

yes,SOFATracer follows the Opentracing specification.According to Opentracing semantics, SpanContext is used for transparent transmission over the network. If tracerId and spanId are placed in Span, but Span is not used for cross-process delivery, the trace will not be correctly represented.
