### ISSUE TITLE
SOFA

### ISSUE THREAD

**Issue by jingze12** [sofastack/sofa-tracer#221]

**Comment by glmapper** [comment]
> ### Your question
> describe your question clearly
> 
> ### Your scenes
> describe your use scenes (why need this feature)
> 
> ### Your advice
> describe the advice or solution you'd like
> 
> ### Environment
> * SOFATracer version:
> * JVM version (e.g. `java -version`):
> * OS version (e.g. `uname -a`):
> * Maven version:
> * IDE version:

Please provide a little more information.

**Comment by jingze12** [comment]
Environment
SOFATracer version:2.4.1-SNAPSHOT
JVM version (e.g. java -version):1.8

**Comment by glmapper** [comment]
@jingze12 can you provider a simple  ?

**Comment by glmapper** [comment]
This issue will be closed, if you have any questions, you can open it again.
