### ISSUE TITLE
Support Spring Cloud Gateway

### ISSUE THREAD

**Issue by shengxiang205** [sofastack/sofa-tracer#226]
### Your question

we need support spring cloud gateway

### Your scenes

we using spring-cloud-gateway as our api gateway

### Your advice

create gateway filter the same way as webfilter

### Environment

- SOFATracer version: 3.0.2
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
open in #293
