### ISSUE TITLE
无法扩展DataSourceClientTracer.getClientDigestEncoder()

### ISSUE THREAD

**Issue by panbdun** [sofastack/sofa-tracer#229]
com.alipay.sofa.tracer.plugins.datasource.tracer.DataSourceClientTracer.getClientDigestEncoder() 中方法没办扩展，默认是json格式，现在不能扩展使用XStringBuilder新写一个Encoder， 能否扩展下

 @Override
    protected SpanEncoder<SofaTracerSpan> getClientDigestEncoder() {
        return new DataSourceClientDigestJsonEncoder();
    }

**Comment by glmapper** [comment]
> com.alipay.sofa.tracer.plugins.datasource.tracer.DataSourceClientTracer.getClientDigestEncoder() 中方法没办扩展，默认是json格式，现在不能扩展使用XStringBuilder新写一个Encoder， 能否扩展下
> 
> @override
> protected SpanEncoder getClientDigestEncoder() {
> return new DataSourceClientDigestJsonEncoder();
> }

SpanEncoder 是支持扩展的；实现可以参考 mvc 插件的实现方式。编码方式可以通过配置文件的方式来指定具体的 SpanEncoder 。

目前 SOFATracer 仅支持了 json 的方式，XStringBuilder 方式你可以描述下具体的背景，如果多数场景下都有支持 XStringBuilder 编码需求，我们将会考虑支持这种方式。

**Comment by panbdun** [comment]
主要json方法太占空间

com.alipay.sofa.tracer.plugins.springmvc.SpringMvcTracer.java下的实现

@Override
    protected SpanEncoder<SofaTracerSpan> getServerDigestEncoder() {
        if (Boolean.TRUE.toString().equalsIgnoreCase(
            SofaTracerConfiguration.getProperty(SPRING_MVC_JSON_FORMAT_OUTPUT))) {
            return new SpringMvcDigestJsonEncoder();
        } else {
            return new SpringMvcDigestEncoder();
        }
    }

这个可以指定property来灵活切换，

com.alipay.sofa.tracer.plugins.datasource.tracer.DataSourceClientTracer这个是直接new出来，而且SmartDataSource.setClientTracer(DataSourceClientTracer clientTracer);这个参数没有抽象出来而是用的实现类（且构造方法是私有），不能自己实现，不知道你说的配置SpanEncoder  是哪种方式？可否告知

**Comment by glmapper** [comment]
> 主要json方法太占空间
> 
> com.alipay.sofa.tracer.plugins.springmvc.SpringMvcTracer.java下的实现
> 
> @override
> protected SpanEncoder getServerDigestEncoder() {
> if (Boolean.TRUE.toString().equalsIgnoreCase(
> SofaTracerConfiguration.getProperty(SPRING_MVC_JSON_FORMAT_OUTPUT))) {
> return new SpringMvcDigestJsonEncoder();
> } else {
> return new SpringMvcDigestEncoder();
> }
> }
> 
> 这个可以指定property来灵活切换，
> 
> com.alipay.sofa.tracer.plugins.datasource.tracer.DataSourceClientTracer这个是直接new出来，而且SmartDataSource.setClientTracer(DataSourceClientTracer clientTracer);这个参数没有抽象出来而是用的实现类（且构造方法是私有），不能自己实现，不知道你说的配置SpanEncoder 是哪种方式？可否告知

Yes, this is currently implemented in SpringMVC; Other plugins for access are equally achievable. If you are interested, you can improve this part of the ability and then PR.

If you pay more attention to this ability in the actual application, we will put this part of the function into the planning as soon as possible.

**Comment by glmapper** [comment]
@zy198804065 2.4.1/3.0.6 版本开始，支持 XStringBuilder 格式。详细配置见 [SOFATracer 配置项
](https://www.sofastack.tech/projects/sofa-tracer/configuration/)
