### ISSUE TITLE
springcloud integrate sofatracer and specify start port error by --server.port=portnumber

### ISSUE THREAD

**Issue by zzps** [sofastack/sofa-tracer#232]
### Describe the bug
java.lang.ClassCastException: org.springframework.core.env.SimpleCommandLinePropertySource cannot be cast to org.springframework.core.env.MapPropertySource
at com.alipay.sofa.infra.listener.SofaBootstrapRunListener.lambda$assemblyLogSetting$1(SofaBootstrapRunListener.java:62)
当我指定端口启动时报如上错误
tracer-sofa-boot-starter，vesion：3.0.5
sofa-tracer-resttmplate-plugin, version : 2.4.0
### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@zzps can you provide a simple demo ?

**Comment by zzps** [comment]
> 
> 
> @zzps can you provide a simple demo ?

好的我就用中文说了，我项目太大不好发你说，我刚才新建了个小demo  maven pom.xml是
`<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>x.y.z</groupId>
  <artifactId>x-y-z</artifactId>
  <version>1.0</version>

  <name>x-y-z</name>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.1.3.RELEASE</version>
  </parent>
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <java.version>1.8</java.version>
    <spring.cloud.version>2.1.1.RELEASE</spring.cloud.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
      <version>${spring.cloud.version}</version>
    </dependency>
    <dependency>
      <groupId>com.alipay.sofa</groupId>
      <artifactId>tracer-sofa-boot-starter</artifactId>
      <version>3.0.5</version>
    </dependency>
    <dependency>
      <groupId>com.alipay.sofa</groupId>
      <artifactId>sofa-tracer-resttmplate-plugin</artifactId>
      <version>2.4.0</version>
    </dependency>
  </dependencies>

  <build>
  </build>
</project>
`
然后一个简单的启动类代码大致是`public static void main( String[] args ) {
        SpringApplication.run(App.class, args);
    }`

然后我用命令行启动java -jar xx.jar   --server.port=9000就报错了
查找报错信息是出在com.alipay.sofa.infra.listener.SofaBootstrapRunListener.class的第62行，可以看到这一行代码是有一个强制转换((MapPropertySource) propertySource).getPropertyNames()  但是我如果通过命令行指定端口的话会有一个SimpleCommandLinePropertySource在enviroment对象里，很显然SimpleCommandLinePropertySource是无法转换成MapPropertySource的，然后就报错了

**Comment by glmapper** [comment]
@zzps 在 SOFATracer 3.x 版本中，没有 resttmplate 插件，这块我们放在下个版本中将 master 上的这部分能力 cheery pick 到 3.x 上。报错的原因是 Springboot 2.1.x 与 Springboot 1.5.x 本身存在兼容性问题

**Comment by zzps** [comment]
> Springboot 1.5.x
嗯，我记得我nacos整合的时候也是遇到因为springcloud版本导致一个监听器生效问题，谢谢，我自己改下源码吧，祝好
