### ISSUE TITLE
BasePreparedStatement的初始化策略问题

### ISSUE THREAD

**Issue by citywalki** [sofastack/sofa-tracer#233]
### Describe the bug
`java.lang.IllegalStateException: BasePreparedStatement has not been initialized
	at com.alipay.sofa.tracer.plugins.datasource.BasePreparedStatement.checkState(BasePreparedStatement.java:98)`

当使用JdbcTemplate.update(JdbcTemplate.java:927)方法，由于tracer-datasource-plugin中的BasePreparedStatement会在getParameterMetaData执行前做checkState，但BasePreparedStatement的initialized是被延迟到第一次执行 SQL时才会被初始化，所以会导致checkState失败。

### Steps to reproduce
调用JdbcTemplate.update(String sql, @Nullable PreparedStatementSetter pss)

### Environment

- SOFATracer version: 3.0.5
- JVM version (e.g. `java -version`): 1.8
- OS version (e.g. `uname -a`): Win10
- Maven version: gradle

**Comment by citywalki** [comment]
bug又没人管吗？

**Comment by glmapper** [comment]
> bug又没人管吗？

这个问题内部已经评审过了，会放在下个 2.4.1 / 3.0.6 版本中修复

**Comment by citywalki** [comment]
> > bug又没人管吗？
> 
> 这个问题内部已经评审过了，会放在下个 2.4.1 / 3.0.6 版本中修复

那就好，我只是怕没人理会那就不太棒了

**Comment by taotao365s** [comment]
首先，sofa-tracer-datasource-plugin 思路确实不错

这种错误太致命了，直接影响生产环境
这种场景下也会出现 `BasePreparedStatement has not been initialized `

- mybatis & tkmapper
- druid datasource

````
 @Autowired
    private SqlSessionFactory sqlSessionFactory;

@Override
    @Transactional(rollbackFor = Exception.class)
    public void insertBatch(List list) {

        SqlSession sqlSession = sqlSessionFactory.openSession(ExecutorType.BATCH);
        XXMapper mapper = sqlSession.getMapper(XXMapper.class);

        for (int i = 0; i < list.size(); i++) {
            mapper.insertSelective(list.get(i));
            if (i % Const.DB_BATCH_SIZE == (Const.DB_BATCH_SIZE - 1)) {
                sqlSession.flushStatements();
            }
        }
        sqlSession.flushStatements();
    }
````


debug了一下
![image](https://user-images.githubusercontent.com/1212932/61293919-5113cb80-a807-11e9-81f2-557d19a846a9.png)
目测stmt被缓存起来了，而这里优先使用了delegate.queryTimeout的方法

**Comment by taotao365s** [comment]
@iamcyw do you have demo code?

**Comment by citywalki** [comment]
> @iamcyw do you have demo code?

抱歉没有，我只是阅读jdbctemlate代码
