### ISSUE TITLE
兼容spring boot1吗

### ISSUE THREAD

**Issue by chenghuanhuan** [sofastack/sofa-tracer#234]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by chenghuanhuan** [comment]
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.properties.bind.Binder

**Comment by glmapper** [comment]
> Caused by: java.lang.ClassNotFoundException: org.springframework.boot.context.properties.bind.Binder
你用的 tracer 版本是多少，如果是 springboot 1.x 的话可以使用 tracer 2.4 版本

**Comment by glmapper** [comment]
Since there is no feedback for a long time, please close this issue here first. If you have any questions, you can open it again.
