### ISSUE TITLE
The dataSource annotation does not automatically generate a SmartDataSource instance.

### ISSUE THREAD

**Issue by panbdun** [sofastack/sofa-tracer#251]
代码配置：
@Bean("dataSourceOfDruid")
@Qualifier("dataSourceOfDruid")
public DataSource dataSourceOfDruid() {
	DruidDataSource dataSource = new DruidDataSource();

	dataSource.setUrl(jdbcUrl);
	dataSource.setUsername(username);
	dataSource.setPassword(password);
	dataSource.setDriverClassName(driverClassName);

	// configuration
	dataSource.setInitialSize(minIdle);
	dataSource.setMinIdle(minIdle);
	dataSource.setMaxActive(maxPoolSize);
	dataSource.setMaxWait(connectionTimeoutMs);
	dataSource.setTimeBetweenEvictionRunsMillis(60000);
	dataSource.setMinEvictableIdleTimeMillis(300000);
	dataSource.setValidationQuery(connectionTestQuery);
	dataSource.setTestWhileIdle(true);
	dataSource.setTestOnBorrow(false);
	dataSource.setTestOnReturn(false);

	// 打开PSCache，并且指定每个连接上PSCache的大小
	dataSource.setPoolPreparedStatements(true);
	dataSource.setMaxPoolPreparedStatementPerConnectionSize(20);

	return dataSource;
}

源码：DataSourceBeanFactoryPostProcessor.postProcessBeanFactory()

BeanDefinition dataSource = getBeanDefinition(beanName, beanFactory);
//注释模式，dataSource.getBeanClassName()为Null
if (DataSourceUtils.isDruidDataSource(dataSource.getBeanClassName())) {
	createDataSourceProxy(beanFactory, beanName, dataSource,
		DataSourceUtils.getDruidJdbcUrlKey());
} else if (DataSourceUtils.isC3p0DataSource(dataSource.getBeanClassName())) {
	createDataSourceProxy(beanFactory, beanName, dataSource,
		DataSourceUtils.getC3p0JdbcUrlKey());
} else if (DataSourceUtils.isDbcpDataSource(dataSource.getBeanClassName())) {
	createDataSourceProxy(beanFactory, beanName, dataSource,
		DataSourceUtils.getDbcpJdbcUrlKey());
} else if (DataSourceUtils.isTomcatDataSource(dataSource.getBeanClassName())) {
	createDataSourceProxy(beanFactory, beanName, dataSource,
		DataSourceUtils.getTomcatJdbcUrlKey());
} else if (DataSourceUtils.isHikariDataSource(dataSource.getBeanClassName())) {
	createDataSourceProxy(beanFactory, beanName, dataSource,
		DataSourceUtils.getHikariJdbcUrlKey());
}

**Comment by glmapper** [comment]
@zy198804065 哪个版本？

**Comment by panbdun** [comment]
> @zy198804065 哪个版本？

@glmapper   3.0.2
