### ISSUE TITLE
When did the sofa-tracer upgrade to the official 3.0.6 version, now the central warehouse does not have

### ISSUE THREAD

**Issue by LightShine** [sofastack/sofa-tracer#252]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@LightShine 本周 release
