### ISSUE TITLE
Two sampling calculations

### ISSUE THREAD

**Issue by cijianshaonian** [sofastack/sofa-tracer#256]
### Your question

sofaTracer 在采样计算时rootSpan为什么会计算两次？第一次是生成span时，第二次是在上报前又计算了一次，这两次计算产生的结果可能是不一样的，这样设计的原因是什么？

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@cijianshaonian 允许应用本身控制日志量而不依赖请求入口的采样计算

**Comment by cijianshaonian** [comment]
在请求入口的采样计算已经随着链路传到下游了，如果上报前的计算和入口计算不一致，就会产生链路收集不完整的问题

**Comment by glmapper** [comment]
> 在请求入口的采样计算已经随着链路传到下游了，如果上报前的计算和入口计算不一致，就会产生链路收集不完整的问题

是的，这种情况会存在风险。单从应用本身控制日志量而不依赖请求入口的采样计算这种方式是需要被移除的，感谢关注。这个在下个版本将会重新考虑采样这块逻辑的优化。

**Comment by glmapper** [comment]
> 在请求入口的采样计算已经随着链路传到下游了，如果上报前的计算和入口计算不一致，就会产生链路收集不完整的问题

```java
 // sampler is support &  current span is root span
 if (this.getSampler() != null && span.getParentSofaTracerSpan() == null) {
           span.getSofaTracerSpanContext().setSampled(this.getSampler().sample(span).isSampled());
}
```

span.getParentSofaTracerSpan() == null 这里表明其父类 span 是 null ，也就表示当前 span 是 root span

**Comment by cijianshaonian** [comment]
@glmapper 如果root span在入口处计算是需要采样的，此结果随链路传递到下游，下游的span已经记录上报了，root span在上报前又计算了一次，这次计算的结果可能是不需要上报的，这就产生了链路不完整的问题了

**Comment by glmapper** [comment]
> @glmapper 如果root span在入口处计算是需要采样的，此结果随链路传递到下游，下游的span已经记录上报了，root span在上报前又计算了一次，这次计算的结果可能是不需要上报的，这就产生了链路不完整的问题了

A -> B -> C -> D -> E 。 A 作为 root span 计算得到的 sampler 是 true ，假设 C 这里上报时重新计算了 sampler ，结果是 false ，此时A、 B 的 spanContext 中sampler 均是 true .

* C child_of B , C 中执行 上报时  span.getParentSofaTracerSpan() 不为 null，因此不会受到其自身采样计算影响。
* 这里计算的原因：非常规构建 SofaTracerSpanContext 兼容处理

你可以提供下你认为有问题的一条链路，我们一起看下

**Comment by cijianshaonian** [comment]
> > @glmapper 如果root span在入口处计算是需要采样的，此结果随链路传递到下游，下游的span已经记录上报了，root span在上报前又计算了一次，这次计算的结果可能是不需要上报的，这就产生了链路不完整的问题了
> 
> A -> B -> C -> D -> E 。 A 作为 root span 计算得到的 sampler 是 true ，假设 C 这里上报时重新计算了 sampler ，结果是 false ，此时A、 B 的 spanContext 中sampler 均是 true .
> 
> * C child_of B , C 中执行 上报时  span.getParentSofaTracerSpan() 不为 null，因此不会受到其自身采样计算影响。
> * 这里计算的原因：非常规构建 SofaTracerSpanContext 兼容处理
> 
> 你可以提供下你认为有问题的一条链路，我们一起看下

A -> B -> C -> D -> E ,A作为root span计算结果为true，它会把他的结果随链路传递下去，B,C,D,E都会使用A的计算结果，而不会重新计算，但是A在作为root span在上报前又重新计算了一次，这次的结果可能和之前的计算结果不一致，这就会导致A没有上报，但B,C,D,E上报了

**Comment by glmapper** [comment]
[这次的结果可能和之前的计算结果不一致，这就会导致A没有上报，但B,C,D,E上报了]  

你有考虑过 A 存在多种采样的可能性吗？

**Comment by glmapper** [comment]
@cijianshaonian   i will close the issue. if  any other questions , you can open it again
