### ISSUE TITLE
Spanid is not displayed correctly in Zipkin

### ISSUE THREAD

**Issue by qingfeng-bi** [sofastack/sofa-tracer#287]
### Describe the bug
Same traceid, the value of spanid in the file (spring-mvc-digest.log) is "0", but it appears as “af63ad4c86019caf” in Zipkin.

### Expected behavior
The value of spanid should be "0".
### Actual behavior
The value of spanid is "af63ad4c86019caf".
### Steps to reproduce
Run the demo application "tracer-sample-with-zipkin", and visit http: / / localhost: 8080 / hellozipkin through browser.
### Environment

- SOFATracer version: 2.4.1-SNAPSHOT
- JVM version (e.g. `java -version`): Oracle jdk1.8.0_221
- OS version (e.g. `uname -a`): Windws10 64bit
- Maven version: apache-maven-3.3.9
- IDE version: IntelliJ IDEA Community Edition 2019.1.3
- ZIPKIN version: 2.16.2
- SOFABoot Version: 2.5.2

**Comment by glmapper** [comment]
Normal logic, actually will do a conversion
