### ISSUE TITLE
Can link tracking increase the whitelist or blacklist function?

### ISSUE THREAD

**Issue by qingfeng-bi** [sofastack/sofa-tracer#292]
链路是否可以增加白名单或黑名单功能，来指定或过滤哪些请求需要跟踪，哪些请求不需要跟踪。因为当微服务在k8s上部署时，会有很多心跳检查的请求，这些频繁的心跳检查请求都会被上报到zipkin中，相对来讲可视为“垃圾数据”。谢谢。

**Comment by glmapper** [comment]
> 链路是否可以增加白名单或黑名单功能，来指定或过滤哪些请求需要跟踪，哪些请求不需要跟踪。因为当微服务在k8s上部署时，会有很多心跳检查的请求，这些频繁的心跳检查请求都会被上报到zipkin中，相对来讲可视为“垃圾数据”。谢谢。

可以通过自定义采样规则来解决你的问题 ，参考：[自定义采样规则](https://www.sofastack.tech/projects/sofa-tracer/sampler/)

**Comment by qingfeng-bi** [comment]
已经验证，自定义采样规则只能控制心跳检查的请求是否打印到日志里，不能控制是否上报到zipkin。如何控制是否上报到zipkin呢？

**Comment by glmapper** [comment]
可以提交一个pr，当上报zipkin时做下采样检验:smile:

**Comment by qingfeng-bi** [comment]
已经提交pr了，显示Travis CI  Build Failed 是什么原因呢？我用jdk1.8编译的，没用openjdk。
