### ISSUE TITLE
How to use the dubbo protocol in SOFARPC for link tracking with SOFATracer

### ISSUE THREAD

**Issue by lihangang** [sofastack/sofa-tracer#304]
### Environment

- SOFATracer version: 3.0.5
- JVM version (jdk1.8):
- Maven version: 3.2.5
- IDE version: eclipse4.7

**Comment by glmapper** [comment]
@lihangang can you provide a simple demo project?

**Comment by lihangang** [comment]
hi,&nbsp;This attachment is simple demo project ,&nbsp;or this URL: https://github.com/lihangang/Ghl_demo



===================
Best Regards!
lihangang&nbsp;
Mobeli：18598279907
E-Mail：372397387@qq.com
===================


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"GuoLei Song"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 晚上9:21
收件人:&nbsp;"sofastack/sofa-tracer"<sofa-tracer@noreply.github.com&gt;;
抄送:&nbsp;"Allen"<372397387@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [sofastack/sofa-tracer] How to use the dubbo protocol in SOFARPC for link tracking with SOFATracer (#304)




@lihangang can you provide a simple demo project?

**Comment by lihangang** [comment]
hi , What's the progress of this problem , thinks

**Comment by glmapper** [comment]
@lihangang it's OK.

![image](https://user-images.githubusercontent.com/35319286/69722055-250f3c00-1151-11ea-9d3a-3c1532415c62.png)


the pom.xml here:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.alipay.sofa</groupId>
		<artifactId>sofaboot-dependencies</artifactId>
		<version>3.1.3</version>
	</parent>
	<groupId>com.ghl</groupId>
	<artifactId>ghl-consumer</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>ghl-consumer</name>
	<packaging>jar</packaging>

	<properties>
		<java.version>1.8</java.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<java.version>1.8</java.version>
		<maven.test.skip>true</maven.test.skip>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>healthcheck-sofa-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>rpc-sofa-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>com.alipay.sofa</groupId>
			<artifactId>tracer-sofa-boot-starter</artifactId>
			<version>3.0.8</version>
		</dependency>

		<dependency>
			<artifactId>sofa-tracer-dubbo-plugin</artifactId>
			<groupId>com.alipay.sofa</groupId>
			<version>3.0.8</version>
		</dependency>

		<dependency>
			<artifactId>tracer-core</artifactId>
			<groupId>com.alipay.sofa</groupId>
			<version>3.0.8</version>
		</dependency>

		<dependency>
			<artifactId>tracer-extensions</artifactId>
			<groupId>com.alipay.sofa</groupId>
			<version>3.0.8</version>
		</dependency>

		<dependency>
			<groupId>io.zipkin.zipkin2</groupId>
			<artifactId>zipkin</artifactId>
		</dependency>
		<dependency>
			<groupId>io.zipkin.reporter2</groupId>
			<artifactId>zipkin-reporter</artifactId>
		</dependency>

	</dependencies>
</project>

```

> To better solve the problem, if you provide a demo , you must provide the way to start your project , also you should resolve your project before.

**Comment by lihangang** [comment]
Hi , The tracking of MVC is always possible, but I want to know is the tracking of softrpc in Dubbo protocol  , I don't see the rpc-digest.log 
![image](https://user-images.githubusercontent.com/33613388/69771386-92f64a80-11c7-11ea-908b-29ae8f52b3c1.png)
![image](https://user-images.githubusercontent.com/33613388/69771276-3c890c00-11c7-11ea-88d8-07cf367c788e.png)

**Comment by glmapper** [comment]
just see this project: https://github.com/glmapper/Ghl_demo
here is the Zipkin ui show: 
![image](https://user-images.githubusercontent.com/35319286/69773624-4b26f180-11ce-11ea-826b-aa3df43d3ab0.png)

**Comment by lihangang** [comment]
hi, Why don't the tracking of MVC ?  I don't see the spring-mvc-digest.log  , I need tracking for SpringMCV and SofaRPC .
![image](https://user-images.githubusercontent.com/33613388/69781435-20966200-11e9-11ea-958f-da9ef0e2c13c.png)

**Comment by lihangang** [comment]
hi, Why don't the tracking of MVC ? I don't see the spring-mvc-digest.log , I need tracking for SpringMCV and SofaRPC .
![image](https://user-images.githubusercontent.com/33613388/69782568-5f79e700-11ec-11ea-9248-0b8f68fd5e39.png)
