### ISSUE TITLE
SofaTracerFeignClient在使用feign url直接访问并使用链路跟踪时报UnsupportedOperationException

### ISSUE THREAD

**Issue by 99246255** [sofastack/sofa-tracer#312]
### Describe the bug
feign同时使用注册中心获取和域名直连的方式
@FeignClient(value = "${服务名}")、@FeignClient(name = "XXXClient",url = "http://xxxxx/")
通过服务名的链路跟踪无问题，通过域名访问的方式会报以下错误:
```
java.lang.RuntimeException: java.lang.UnsupportedOperationException
	at com.alipay.sofa.tracer.plugins.springcloud.instruments.feign.SofaTracerFeignClient.execute(SofaTracerFeignClient.java:67)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:108)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
```
问题原因：
SynchronousMethodHandler executeAndDecode方法中
生成Request 

    Request request = this.targetRequest(template);
   实际生成代码调用
   

    Request.create(this.method, this.url(), this.headers(), this.requestBody());

而this.headers方法返回的是Collections.unmodifiableMap的
```
   public Map<String, Collection<String>> headers() {
        Map<String, Collection<String>> headerMap = new TreeMap(String.CASE_INSENSITIVE_ORDER);
        this.headers.forEach((key, headerTemplate) -> {
            List<String> values = new ArrayList(headerTemplate.getValues());
            if (!values.isEmpty()) {
                headerMap.put(key, Collections.unmodifiableList(values));
            }

        });
        return Collections.unmodifiableMap(headerMap);
    }
   ```
   后面实际this.delegate.execute的时候
   SofaTracerFeignClient中会在请求头添加链路跟踪信息。
   `appendRequestSpanTagsAndInject(request, sofaTracerSpan);`
   然后在此处抛出异常

- SOFATracer version: 3.0.8
- JVM version (e.g. `java -version`):1.8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@99246255 使用域名方式用resttemple

**Comment by 99246255** [comment]
对外API接口基本都是用feign的,这种可以改SofaTracerFeignClient实现，appendRequestSpanTagsAndInject(request, sofaTracerSpan)遇到UnsupportedOperationException重新构造一个header可编辑的request就行

**Comment by glmapper** [comment]
> 对外API接口基本都是用feign的,这种可以改SofaTracerFeignClient实现，appendRequestSpanTagsAndInject(request, sofaTracerSpan)遇到UnsupportedOperationException重新构造一个header可编辑的request就行

欢迎提交 PR ，😄

**Comment by alanhan02** [comment]
Another solution:
Define class SofaTracerFeignInterceptor implements RequestInterceptor， override the method 'apply'. Inject trace data into request header by RequestTemplate.

**Comment by zzps** [comment]
我项目中的feign-core是10.10.1版本，feign.Request类中的170行headers方法直接是返回`Collections.unmodifiableMap(headers)`，这个操作是真把我搞死，不过它又有一个口子RequestTemplate可以放，但是sofatracer没有进行适配，我看都一年不更新了，是不是烂尾了啊

**Comment by glmapper** [comment]
> 我项目中的feign-core是10.10.1版本，feign.Request类中的170行headers方法直接是返回`Collections.unmodifiableMap(headers)`，这个操作是真把我搞死，不过它又有一个口子RequestTemplate可以放，但是sofatracer没有进行适配，我看都一年不更新了，是不是烂尾了啊

3.1.0 计划本周 release，关于这个问题相关 PR 已经 ready，如果你有其他更好的解决方案，也欢迎提供 PR

**Comment by songcan** [comment]
使用高版本的spring boot 报错 UnsupportedOperationException
，这个什么时候发布版本呢？
