### ISSUE TITLE
Is sofaTracerSpanReportListener method of SofaTracerAutoConfiguration class missing a row SpanReportListenerHolder.clear ();

### ISSUE THREAD

**Issue by gjpine** [sofastack/sofa-tracer#319]
在使用devtools工具开发的时候，SofaTracerAutoConfiguration.sofaTracerSpanReportListener方法里面没有先清理之前SpanReportListenerHolder保存listeners，导致每次热更新的时候，listeners都被重复添加。

**Comment by glmapper** [comment]
可以提交一个pr修复此问题:grinning:

**Comment by glmapper** [comment]
Since there has been no feedback for a long time, we will close this issue first, and then open it if in doubt.
