### ISSUE TITLE
少提交一个类

### ISSUE THREAD

**Issue by leshalv** [sofastack/sofa-tracer#322]
![image](https://user-images.githubusercontent.com/30397655/71239858-8e463180-2342-11ea-96f7-0df3fa70d2e1.png)

**Comment by glmapper** [comment]
@leshalv SofaTracer 也是在 tracer-core 中，麻烦提供下其他一些具体信息：
* 如果是使用，请提供版本
* 如果是看源码，请提供分支或者 tag

**Comment by leshalv** [comment]
我用idea clone的主分支

**Comment by glmapper** [comment]
@leshalv  https://github.com/sofastack/sofa-tracer/blob/master/tracer-core/src/main/java/com/alipay/common/tracer/core/SofaTracer.java

**Comment by leshalv** [comment]
好怪，我重新clone 试试
