### ISSUE TITLE
Dependency conflict, severe bug

### ISSUE THREAD

**Issue by zzps** [sofastack/sofa-tracer#323]
rpc-sofa-boot-starter:6.0.4
tracer-sofa-boot-starter:3.2.1
描述：项目用以上进行整合时，tracer-sofa-boot-starter所引入的sofa-boot-autoconfigure包中的
SofaRuntimeAutoConfiguration.class依赖的SofaRuntimeConfigurationProperties.class在
rpc-sofa-boot-starter所依赖的runtime-sofa-boot-starter中，但是类路径已经改了，会报ClassNotFoundException异常。
将rpc-sofa-boot-starter所依赖的runtime-sofa-boot-starter排除，
手动引入runtime-sofa-boot-starter:3.2.1，则发现ProviderConfigContainer.class分别在
tracer-sofa-boot-starter所引入的sofa-boot-autoconfigure包中和rpc-sofa-boot-starter包中进行了注入bean，注入两次报错。
建议：同一家的不同项目进行整合的时候多考虑兼容性

**Comment by glmapper** [comment]
@zzps https://github.com/sofastack/sofa-tracer/issues/320 从 SOFABoot 3.2.x 版本开始，各组件，包括 tracer/rpc 等 starter 均已统一交由 SOFABoot 管理，见：https://github.com/sofastack/sofa-boot/tree/master/sofa-boot-project/sofa-boot-starters 。但是为了保持 starter 版本的兼容和延续性，各个组件 starter 会在自己仓库中保持适当更新。例如 tracer 将更新 starter 到 3.1.0 版本，后续版本将不在更新，统一跟 SOFABoot 版本迭代；你的问题把  rpc-sofa-boot-starter 版本改成 3.2.1 版本即可
