### ISSUE TITLE
Does the digest log support zipkin&#39;s json format?

### ISSUE THREAD

**Issue by qimei8685** [sofastack/sofa-tracer#346]
### Your question
目前落盘的摘要log是固定格式的，能否直接以zipkin的json数据格式落盘？
如果可以如何操作？

**Comment by glmapper** [comment]
@qimei8685 使用自定义 report ： https://www.sofastack.tech/projects/sofa-tracer/reporter-custom/  + ZipkinV2SpanAdapter 来实现

**Comment by qimei8685** [comment]
> @qimei8685 使用自定义 report ： https://www.sofastack.tech/projects/sofa-tracer/reporter-custom/ + ZipkinV2SpanAdapter 来实现
@glmapper 
1. 添加了com.alipay.sofa.tracer.reporter-name这个配置，自己的reporter的bean也初始化了，但是public void report(SofaTracerSpan sofaTracerSpan)方法并没有被调用，默认调用的还是DiskReporterImpl
2. 自定义的reporter和原来打印摘要log的reporter是什么关系？共存的吗？

**Comment by glmapper** [comment]
@qimei8685 可以提供一个简单的 demo 看下吗？

**Comment by glmapper** [comment]
Since there has been no feedback for a long time, we will close this issue first, and then open it if in doubt.
