### ISSUE TITLE
If you use p6spy to monitor sql in Spring Boot project, SOFATracer starts abnormally

### ISSUE THREAD

**Issue by dong-gy** [sofastack/sofa-tracer#347]
项目中使用SOFATracer，如果数据库使用p6spy做数据库监控，SOFATracer就无法进行sql语句的链路追踪
maven：
![image](https://user-images.githubusercontent.com/48462501/75650786-f80f7f80-5c91-11ea-9f01-e7e50e5c150a.png)
properties:
![image](https://user-images.githubusercontent.com/48462501/75650865-255c2d80-5c92-11ea-810e-a47530d71043.png)
Spring boot整合p6spydemo:
https://www.jianshu.com/p/42c35b320e84

**Comment by glmapper** [comment]
@dong-gy  see #308 . we will merge this pr to support hikari data source
