### ISSUE TITLE
日志采样率较低时如何保证关键信息不遗漏

### ISSUE THREAD

**Issue by DraperChen** [sofastack/sofa-tracer#354]
### Your question

出于性能和资源考虑，采样率较低时，能否保证不遗漏关键的链路信息：错误、超时等

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@DraperChen 采样从链路产生开始就会决定当前log 是否被落盘；如果采样率很低，是无法保证不遗漏的。你可以通过[自定义采样](https://www.sofastack.tech/projects/sofa-tracer/sampler/) 来收集你关注的信息
