### ISSUE TITLE
traceid请求串联

### ISSUE THREAD

**Issue by JemyXiao** [sofastack/sofa-tracer#356]
### Your question

springMvc和dubbo请求traceid可以串联起来吗？如何串联

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@JemyXiao 只要是在一个请求链路上的，tracerId 就是同一个。你可以参考 https://github.com/sofastack-guides/sofa-tracer-guides tracer 的案例工程，将 SpringMVC 和 Dubbo 跑在一起观察下。
