### ISSUE TITLE
feign-core 10.7.x SofaTracerFeignClient inject error

### ISSUE THREAD

**Issue by alanhan02** [sofastack/sofa-tracer#360]
### Your question

当使用高版本的Spring-Cloud时，例如feign-core为10.7.x，Request对象的headers属性会被包装为Collections.unmodifiableMap(headers)返回，无法通过put进行请求头的数据注入；

### Your scenes

SofaTracer作为插件接入高版本Spring-Cloud项目

### Your advice

应该如何处理？通过RequestInterceptor拦截器么？

### Environment

- SOFATracer version: 3.x
- JVM version (e.g. `java -version`): jdk 1.8
- OS version (e.g. `uname -a`): windows
- Maven version: 3.5
- IDE version: 2019.3.3

**Comment by glmapper** [comment]
related to #312   #318
