### ISSUE TITLE
NPE issues when users extend Reporter

### ISSUE THREAD

**Issue by chenmudu** [sofastack/sofa-tracer#363]
SpringBoot : 2.1.14.RELEASE
JDK: 1.8.1
自定义扩展Reporter，实现Reporter，并在此注入Spring容器Bean，出现NPE,我应该如何做，才可以把SofaTracerSpan里的Tag数据通过MQ发送到目的地。

**Comment by glmapper** [comment]
> Spring

can you provide a simple case?

**Comment by chenmudu** [comment]
Hi:
Yes, such as this: after I implemented my own Reporter in the Spring container, I want to send it to the heterogeneous application B through MQ to implement some other operations, such as data cleaning or other;
`public class CustomizedReporter implements Reporter {

    //....

    //....

    @autowired
    private AmqpTemplate amqpTemaplate;

    @Override
    public String getReporterType() {
        //....
        return "CustomizedReporter";
    }

    @Override
    public void report(SofaTracerSpan sofaTracerSpan) {
        //....
       // report 
        send.send(logMessage); // or use rpc to transfer data?
    }

    @Override
    public void close() {
        // ignore
        //....
    }
}`


What is the general reason? Is it because the reporting class is initialized at the initial stage of the Web? I want to get the cause and solution of this kind of problem from you.

But I found that the injected Template object is null, how to achieve my needs, I need help urgently. Thank you！
