### ISSUE TITLE
Is there any plan to the RabbitMQ Plugins

### ISSUE THREAD

**Issue by edgeowner** [sofastack/sofa-tracer#367]
### Your question

describe your question clearly

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by chenmudu** [comment]
Maybe can transfer this issue to me. I can try it.
