### ISSUE TITLE
建议研发sofa-tracer-agent

### ISSUE THREAD

**Issue by taotao365s** [sofastack/sofa-tracer#373]
### Your question

无改造接入是目前的趋势，可参考skywalking、Elastic APM等业界标杆产品

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@spyvip SOFATracer 的埋点机制与 agent 是完全不一样的，目前业界也有基于 agent 做的非常好的产品（sw），所以我们暂时没有计划支持 sofa tracer agent 版本
