### ISSUE TITLE
traceId is not unique

### ISSUE THREAD

**Issue by taotao365s** [sofastack/sofa-tracer#383]
### Describe the bug
traceid is not unique in large data

![image](https://user-images.githubusercontent.com/1212932/92197090-5caad180-eea3-11ea-9f4d-b2732fa47746.png)

### Environment

- SOFATracer version: 3.0.12
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@spyvip According to the rules of the generation of tracerId, we consider the enough scenes to ensure that its uniqueness;Through the screenshot you provide, we can't catch the key information to verify this.If you can, please provide relevant repetition code.

**Comment by glmapper** [comment]
related to #235
