### ISSUE TITLE
spanid的生成规则

### ISSUE THREAD

**Issue by yttas** [sofastack/sofa-tracer#388]
### Your question

我现在的demo写了两个spring boot项目，基于slf4j打印了parentid，但是A里面调用了B，打印出来的spanid。B是0。A的spanid是0.1.1，parentid是0.1
按着spanid的生成规则A的spanid是0.1，parentid是0？

### Your scenes

describe your use scenes (why need this feature)

### Your advice

describe the advice or solution you'd like

### Environment

- SOFATracer version:
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@yttas A -> B 的调用方式是什么？能否提供一个简单的 demo

**Comment by yttas** [comment]
感谢老师！！
具体的demo代码放在附件里了。
其中tracer-consumer-slf4j 调用 tracer-service-slf4j，调用的语句就是直接使用restTemplate.getForObject。


spring boot的代码是仿照着sofatracer的git里面的扩展slf4j写的。
（https://github.com/sofastack-guides/sofa-tracer-guides/tree/master/tracer-sample-with-slf4j）
由于刚刚开始接触这些，给您添麻烦了，万分感谢您的回信。









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sofastack/sofa-tracer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 晚上9:07
收件人:&nbsp;"sofastack/sofa-tracer"<sofa-tracer@noreply.github.com&gt;;
抄送:&nbsp;"1270662208"<1270662208@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [sofastack/sofa-tracer] spanid的生成规则 (#388)





 
@yttas A -&gt; B 的调用方式是什么？能否提供一个简单的 demo
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

slf4jDemo.zip (64.33M, 2020年10月24日 21:12 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=776437372ed69bcf75a08b7c1465531b005356065307000618550f055448555251501a0f03575119060554535150520c0c015100326861475902035d76000c5b1b1e5e473258&code=5d772ea4

**Comment by glmapper** [comment]
@yttas 代码有 git 仓库吗？我拿到的代码中没有看到你扩展 将 parentid 放在 MDC 的逻辑

**Comment by yttas** [comment]
老师，因为我想先用简单的方法把这个parentid给输出出来，所以我直接对sofa-tracer里面的这个tracer-extensions源码进行修改了，在里面直接mdc.put进行parentid ，然后修改之后直接打包成新版本的依赖，我在我的spring mvc的应用代码就是依赖我自己打包的这个新的tracer-extension了。所以具体的添加在这个Tracer-extensions里面。
Tracer-extensions修改之后在附件里面；


还有就是用sofatracerslf4j扩展的依赖包打印log的时候也是能看出来，traceid是0.1.1
git地址：https://github.com/yttas/tracer-demo


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "sofastack/sofa-tracer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月1日(星期四) 下午5:08
收件人:&nbsp;"sofastack/sofa-tracer"<sofa-tracer@noreply.github.com&gt;;
抄送:&nbsp;"1270662208"<1270662208@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [sofastack/sofa-tracer] spanid的生成规则 (#388)





 
@yttas 代码有 git 仓库吗？我拿到的代码中没有看到你扩展 将 parentid 放在 MDC 的逻辑

**Comment by glmapper** [comment]
@yttas is there any other problems?

**Comment by glmapper** [comment]
@yttas we will close this issue , if you have any other feedback, you can reopen this again.
