### ISSUE TITLE
时钟回拨情况下TraceId重复

### ISSUE THREAD

**Issue by gitYupan** [sofastack/sofa-tracer#389]
### Your question
TraceId 产生规则是： 服务器 IP + 产生 ID 时候的时间 + 自增序列 + 当前进程号
上面的生成规则在时钟回拨的情况下，产生的TraceId应该会重复

**Comment by glmapper** [comment]
@gitYupan 产生 tracerId 的几个条件还是比较严格的，时钟回拨的场景下是可能会存在产生相同 TraceId 的情况；如果有兴趣可以提个 PR 支持下允许自定义 tracerId

**Comment by glmapper** [comment]
to #235
