### ISSUE TITLE
 When will the trace data be bridged to Open-Telemetry.

### ISSUE THREAD

**Issue by chenmudu** [sofastack/sofa-tracer#413]
### Your question

According to personal opinion, Open-Telemetry will become the standard of observability. When will the trace data be bridged to Open-Telemetry Collector.

### Your advice

Bridge trace data from SOFA Tracer to OpenTelemetry Collector. Thanks a lot.

**Comment by chenmudu** [comment]
@khotyn  Hi, has this issue been discussed yet? What do you think? Thannnnks a lot.

**Comment by khotyn** [comment]
@chenmudu No, you can provide a design document about how to doing this.

**Comment by chenmudu** [comment]
> @chenmudu No, you can provide a design document about how to doing this.

Ok, copy that.
