### ISSUE TITLE
spring boot 2.x logging.path 过期

### ISSUE THREAD

**Issue by DonaldHanSoftWare** [sofastack/sofa-tracer#416]
### Describe the bug

spring boot 2.x版本中，logging.path属性已过期，使用logging.file.path无效

### Environment

- SOFATracer version: latest
- JVM version  1.8
- String boot 2.4.1

**Comment by chenmudu** [comment]
@DonaldHanSoftWare  It seems that the version of SpringBoot that the current version of SOFA-Boot depends on is too low. 
There are currently two solutions: 
 1. Lower the SpringBoot version of the your application. 
 2. Sofa-Boot adapts to the higher version of SpringBoot(Shouldn't be here).
@khotyn @glmapper  Hi, how do you think about it? Thanks.

**Comment by khotyn** [comment]
@chenmudu I think SOFABoot should adapt higher version of SpringBoot. @ujjboy could you take a took at this issue?

**Comment by ujjboy** [comment]
We can add code to `TracerLogRootDaemon.java` and get the property of `logging.file.path` and  `logging.path` at the same time.

https://github.com/sofastack/sofa-tracer/blob/5d74b09f38188b64d313de7a228af584dc011104/tracer-core/src/main/java/com/alipay/common/tracer/core/appender/TracerLogRootDaemon.java#L60-L68

**Comment by glmapper** [comment]
@DonaldHanSoftWare At the current, you can resolve by set SOFA_TRACER_LOGGING_PATH=xx in your properties or -DSOFA_TRACER_LOGGING_PATH=xx or -DloggingRoot=xx , And we will adapter logging.file.path in 3.1.1 version. thank you for your feedback.

**Comment by xyohn** [comment]
> @DonaldHanSoftWare At the current, you can resolve by set SOFA_TRACER_LOGGING_PATH=xx in your properties or -DSOFA_TRACER_LOGGING_PATH=xx or -DloggingRoot=xx , And we will adapter logging.file.path in 3.1.1 version. thank you for your feedback.

hi, i find that it's not merged in the current version ,will it change  in the next version ?
