### ISSUE TITLE
SpringMVC请求日志添加请求体信息

### ISSUE THREAD

**Issue by wtlihao** [sofastack/sofa-tracer#435]
### Your question
目前版本只有方法名字、请求耗时、以及url信息，但是没有请求体信息

### Your scenes
SpringBoot项目集成sofa-tracer收集http请求日志，然后上传到es或者其他日志平台
### Your advice
sofa-tracer源码看是插件的形式去做日志，SpringMvc插件实际也是基于servlet的标准filter去做的参数透传，所以在这里做一些处理

### Environment
- SOFATracer version:最新版
- JVM version (e.g. `java -version`):jdk11
- OS version (e.g. `uname -a`):centos7
- Maven version:3.x
- IDE version:2021.3

**Comment by glmapper** [comment]
@wtlihao 1、请求参数中可能会包括一些敏感信息，直接落在日志，有安全风险，需要做脱敏处理，tracer 在 3.1.1 版本提供了扩展 encoder 的能力 2、http 流在读取之后不可再读，需要包装成 ContentCachingRequestWrapper 或 MultipleReadHttpRequest。

对于 sofa tracer 来说，其更多关注在于链路串联，业务层面需求可以通过 sofa tracer 提供的一些扩展机制进行业务自定义实现，所以这块建议通过手动埋点方式去处理下，将请求体数据落盘或者上报
