### ISSUE TITLE
sofa-tracer-redis-plugin 支持的spring data redis客户端以及jedis客户端版本

### ISSUE THREAD

**Issue by heepy** [sofastack/sofa-tracer#437]
### Your question

sofa-tracer-redis-plugin 是否支持spring data redis 以及相应的starter？
sofa-tracer-redis-plugin 支持的spring data redis以及 jedis版本？支持的最新版本和最老版本是什么？

**Comment by glmapper** [comment]
@heepy see https://github.com/sofastack/sofa-tracer/blob/master/sofa-tracer-plugins/sofa-tracer-redis-plugin/pom.xml
