### ISSUE TITLE
Open Source Promotion Plan 2022 - upgrade opentracing api version & adapter opentelemetry api

### ISSUE THREAD

**Issue by glmapper** [sofastack/sofa-tracer#473]
Currently, sofa-tracer relies on the openTracing version 0.22.0. This version has been out of date for a long time and we need to update to the official recommended stable version. In addition, we need to provide an API layer to accommodate OpentElemetry. 
Tasks:
1、upgrade opentracing version to [release-0.33.0](https://github.com/opentracing/opentracing-java/releases/tag/release-0.33.0)
2、adapter https://opentelemetry.io/docs/migration/opentracing/
3、provide intergration doc and guides

**Comment by seeflood** [comment]
宋老师优秀
我开了个课题征集的 issue https://github.com/sofastack/sofastack.tech/issues/876
![image](https://user-images.githubusercontent.com/26001097/161378805-7ab41d6c-bd69-4a01-89e4-0f6998344df5.png)

**Comment by dinglianghui** [comment]
老师，能不能带我一个，对开源很有兴趣，方便的话加个微信呗dlh1247726484

**Comment by seeflood** [comment]
@dinglianghui 好呀好呀欢迎，不过现在离学生报名还早，可以先看下社区其他活动
比如源码解析
https://github.com/sofastack/sofa-registry/issues/205
https://github.com/mosn/layotto/issues/444

或者 新手任务系列
https://github.com/mosn/layotto/issues/108#issuecomment-872779356

**Comment by vwyuheng** [comment]
老板啥时候升级完成@[glmapper](https://github.com/glmapper)

**Comment by glmapper** [comment]
> 

按照开源之夏去年的进度，学生完整完成项目需要到9-10 月份左右
