### ISSUE TITLE
spring cloud 3中的openfeign支持

### ISSUE THREAD

**Issue by taotao365s** [sofastack/sofa-tracer#475]
### Describe the bug

spring cloud 3中移除了ribbon的支持，使用了自定义的rebalance
![image](https://user-images.githubusercontent.com/1212932/166185400-a4c913f3-2da2-4046-971a-88eba8877cdd.png)

### Environment

- SOFATracer version: 3.1.0
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by glmapper** [comment]
@taotao365s 高版本的 spring cloud 支持确实存在问题，感谢反馈；如果有兴趣可以提供一个 pr 来支持此功能

**Comment by glmapper** [comment]
https://github.com/sofastack/sofa-tracer/pull/486 MERGED
