### ISSUE TITLE
sofatracer的tracerId不一定为30位

### ISSUE THREAD

**Issue by JagdtigerI** [sofastack/sofa-tracer#485]
### Describe the bug

![image](https://user-images.githubusercontent.com/25842839/181699050-b2d2b712-3593-4f90-a1be-7dd8c0e789b1.png)

sofaTracer的tracerId无法保证是30位
后五位为pid,pid可能不满5位，也可超过5位
linux 64 位系统 pid 最高 2^22 为4194304

![image](https://user-images.githubusercontent.com/25842839/181699657-1a57c935-c126-4045-b3ca-262f136aee32.png)

### Environment

- SOFATracer version: 3.1.3
- JVM version (e.g. `java -version`): jdk1.8-202
- OS version (e.g. `uname -a`):windows/linux
- Maven version:3.6.1
- IDE version:idea 2019.3.1

**Comment by xzchaoo** [comment]
文档描述有些问题, 没有保证30位. 实践中也不要假设traceId的长度.
