### ISSUE TITLE
sofa-tracer-httpclient-plugin使用httpclient连接池，请求发生异常时,内存泄漏，spanId无限变长

### ISSUE THREAD

**Issue by ddq123456** [sofastack/sofa-tracer#487]
### Describe the bug

使用httpClient使用连接池请求发生异常时，com.alipay.sofa.tracer.plugins.httpclient.interceptor.SofaTracerHttpInterceptor#process(org.apache.http.HttpResponse, org.apache.http.protocol.HttpContext) 无法调用到，导致无法调用sofaTraceContext.pop()，导致内存泄漏，并且spanId 会无限加长(.1.1.1.1.1.1),后续异常请求无限嵌套SofaTracerSpan对象。
![image](https://user-images.githubusercontent.com/25599808/182799998-d81f10e6-87ce-4e12-bdc9-886c47308fc5.png)

### Actual behavior
当http请求失败数量增多，会导致内存泄漏SofaTracerSpan对象和spanId无限增长。
### Environment

- SOFATracer version:3.1.2
- JVM version (e.g. `java -version`):jdk 8
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

暂时我是通过 HttpClient内的RetryHandler重试中处理
![image](https://user-images.githubusercontent.com/25599808/182801745-42982f7d-5390-4b99-98e7-2a4910ccac84.png)

**Comment by ddq123456** [comment]
version=4.5.10
groupId=org.apache.httpcomponents
artifactId=httpclient

**Comment by glmapper** [comment]
@ddq123456 能提供一个 demo 吗？

**Comment by ddq123456** [comment]
[文件.zip](https://github.com/sofastack/sofa-tracer/files/9314813/default.zip)
就定时任务里面调下不能访问的地址，spanId 就会无限制增长下去

> @ddq123456可以提供一个演示吗？

**Comment by ddq123456** [comment]
> @ddq123456 能提供一个 demo 吗？

**Comment by glmapper** [comment]
@ddq123456 看了下你提供的代码，你通过 api 自己处理的 span 的生命周期，没有处理好; 你可以通过 SofaTracerHttpClientBuilder 来构建 httpclient，详见：https://www.sofastack.tech/projects/sofa-tracer/usage-of-httpclient/

**Comment by ddq123456** [comment]
> @ddq123456下你提供的代码，你通过自己的 api 处理跨度的生命周期，没有处理好；你可以通过 SofaTracerHttpClientBuilder 来构建 httpclient，参见：https://www.sofastack.tech/projects/sofa-tracer/usage-of-httpclient/

![image](https://user-images.githubusercontent.com/25599808/187580937-77ddc1e4-b07d-4e10-b9b6-3a1a08c2be06.png)
HttpClientBuilder httpClientBuilder = SofaTracerHttpClientBuilder.clientBuilder(HttpClients.custom()); 

这个我看是有通过 SofaTracerHttpClientBuilder 来构建 httpclient的

**Comment by ddq123456** [comment]
@glmapper  再麻烦看下 这个我看着就是没问题呀，而且我看httpClient的    SofaTracerHttpInterceptor  是无法对 http请求发身异常时的com.alipay.common.tracer.core.tracer.AbstractTracer#clientReceive，所以导致的spanId 边长

**Comment by glmapper** [comment]
> 

异常情况下，逻辑有进入到 SofaTracerHttpInterceptor 吗？

**Comment by ddq123456** [comment]
没有

**Comment by glmapper** [comment]
> 没有

提供下堆栈

**Comment by ddq123456** [comment]
调试看不到

**Comment by ddq123456** [comment]
我给你看提供下  org.apache.http.impl.execchain.ProtocolExec  这个类的186  行

**Comment by ddq123456** [comment]
![image](https://user-images.githubusercontent.com/25599808/188455983-65239006-d308-4147-a959-01913b8d1d98.png)

**Comment by glmapper** [comment]
@ddq123456 get，可以把你现在的 demo 在发一下吗？

**Comment by ddq123456** [comment]
![image](https://user-images.githubusercontent.com/25599808/188456301-1ffca4ac-98a0-4863-b730-dbfb9cb8b2e5.png)
相当于HttpRequestInterceptor 能进   HttpResponseInterceptor 无法进入

**Comment by ddq123456** [comment]
[SchulderBean.zip](https://github.com/sofastack/sofa-tracer/files/9490065/SchulderBean.zip)

**Comment by ddq123456** [comment]
version=4.5.10
groupId=org.apache.httpcomponents
artifactId=httpclient

**Comment by glmapper** [comment]
@ddq123456 get, 这种实际上模拟的是服务端跑出异常，没法正常返回的场景，现在你是怎么解决的

**Comment by ddq123456** [comment]
![image](https://user-images.githubusercontent.com/25599808/189512345-986bbb16-e38a-4d06-962b-83fd040e3e29.png)
上面评论里面有，暂时是在判断重试里面处理的

**Comment by ddq123456** [comment]
@glmapper 这个问题好了吗？我看好像代码上没看出来那改了呀
